spring:
  application:
    name: catalogue-service
  lifecycle:
    timeout-per-shutdown-phase: 15s
   
  cloud:
    config: 
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
  datasource:
    username: postgres
    password: P@@SSword2121
    url: jdbc:postgresql://localhost:5433/cataloguedb
    hikari:
      connection-timeout: 2000 #ms
      maximum-pool-size: 5
  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: refresh

polar:
  greeting: Welcome to the local book catalog!