
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/custumer-db
    username: postgres
    password: P@@SSword2121

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    show-sql: true
    generate-ddl: true
    open-in-view: false
    hibernate.ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


#springdoc:
#  swagger-ui:
#    path: /swagger-ui/api-docs.html
